#!/usr/bin/env node

/**
 * install-hook.js
 * 安裝 post-commit hook 到指定的 git repository
 *
 * Usage:
 *   node install-hook.js --target <repo-path>
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ============================================================================
// Config
// ============================================================================

const EVERNOTE_REPO = path.resolve(__dirname, '..');
const GENERATE_NOTE_SCRIPT = path.join(EVERNOTE_REPO, 'scripts', 'generate-note.js');

// ============================================================================
// Helpers
// ============================================================================

function parseArgs() {
  const args = process.argv.slice(2);
  let target = null;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--target') target = args[++i];
  }

  return { target };
}

function checkApiKey() {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.warn('⚠️  Warning: ANTHROPIC_API_KEY environment variable is not set');
    console.warn('   The hook will fail when it tries to generate notes.');
    console.warn('   Set it in your shell profile (~/.bashrc, ~/.zshrc, or System Environment Variables)');
    return false;
  }
  return true;
}

// ============================================================================
// Hook Installation
// ============================================================================

function installHook(targetRepo) {
  const hookPath = path.join(targetRepo, '.git', 'hooks', 'post-commit');
  const hookContent = `#!/bin/sh
# Auto-generate technical notes after each commit
# Generated by Evernote/scripts/install-hook.js

node "${GENERATE_NOTE_SCRIPT.replace(/\\/g, '/')}" \\
  --repo "$(pwd)" \\
  --commits 1 \\
  --auto-commit

exit 0
`;

  // Check if hook already exists
  if (fs.existsSync(hookPath)) {
    const existing = fs.readFileSync(hookPath, 'utf-8');
    if (existing.includes('generate-note.js')) {
      console.log('✅ Hook already installed (found existing generate-note.js reference)');
      return;
    }

    // Backup existing hook
    const backupPath = `${hookPath}.backup`;
    fs.writeFileSync(backupPath, existing, 'utf-8');
    console.log(`📋 Backed up existing hook to: ${path.basename(backupPath)}`);
  }

  // Write hook
  fs.writeFileSync(hookPath, hookContent, 'utf-8');

  // Make executable (Unix)
  if (process.platform !== 'win32') {
    try {
      fs.chmodSync(hookPath, 0o755);
    } catch (err) {
      console.warn('⚠️  Warning: Failed to make hook executable:', err.message);
    }
  }

  console.log('✅ Hook installed successfully');
  console.log(`   Location: ${hookPath}`);
}

// ============================================================================
// Main
// ============================================================================

function main() {
  const { target } = parseArgs();

  if (!target) {
    console.error('❌ Error: --target <repo-path> is required');
    console.error('\nUsage:');
    console.error('  node install-hook.js --target <repo-path>');
    console.error('\nExample:');
    console.error('  node install-hook.js --target C:/Users/jeffb/Desktop/code/CloudPipe');
    process.exit(1);
  }

  const targetRepo = path.resolve(target);

  // Validate target
  if (!fs.existsSync(targetRepo)) {
    console.error(`❌ Error: Repository not found: ${targetRepo}`);
    process.exit(1);
  }

  const gitDir = path.join(targetRepo, '.git');
  if (!fs.existsSync(gitDir)) {
    console.error(`❌ Error: Not a git repository: ${targetRepo}`);
    process.exit(1);
  }

  console.log(`📦 Target repository: ${path.basename(targetRepo)}`);
  console.log(`🔧 Installing post-commit hook...`);

  // Check API key
  checkApiKey();

  // Install hook
  installHook(targetRepo);

  console.log('\n🎉 Done! The hook will now run after each commit in this repo.');
  console.log('   Notes will be auto-generated and committed to the Evernote repo.');
}

main();
